/// Core gameplay and virtual-economy constants.
///
/// This file contains deterministic rules used by the game engine:
/// mining, progression, upgrades, rewards, offline rewards, conversion,
/// missions, and other gameplay limits.
///
/// Important:
/// All values in this file belong to the virtual game economy.
/// They represent simulated values and have no real-world monetary value.
abstract final class GameConstants {
  GameConstants._();

  // ===========================================================================
  // Economy
  // ===========================================================================

  /// The initial virtual USDT balance given to a new player.
  static const double initialUsdtBalance = 0.0;

  /// The virtual USD value represented by one virtual USDT.
  ///
  /// This is intentionally fixed because the application is a simulator and
  /// does not connect to a real exchange or market-price provider.
  static const double virtualUsdtUsdPrice = 1.0;

  /// Minimum amount required for a virtual currency conversion.
  static const double minimumConversionAmount = 0.00000001;

  /// Maximum virtual balance that can be stored for a single currency.
  ///
  /// This protects calculations from accidental runaway values.
  static const double maximumCurrencyBalance = 999999999999.0;

  // ===========================================================================
  // Mining
  // ===========================================================================

  /// Initial mining power of a new player.
  ///
  /// This is an abstract game value and must not be interpreted as a real
  /// cryptocurrency hash rate.
  static const double initialMiningPower = 1.0;

  /// Base virtual USDT reward generated by one unit of mining power
  /// per mining interval.
  static const double baseMiningRewardPerInterval = 0.000001;

  /// Duration of one internal mining calculation interval.
  static const Duration miningInterval = Duration(seconds: 1);

  /// Maximum mining power allowed by the base game.
  static const double maximumMiningPower = 1000000.0;

  /// Maximum number of consecutive mining calculations that can be processed
  /// in one batch.
  static const int maximumMiningCalculationSteps = 86400;

  // ===========================================================================
  // Offline mining
  // ===========================================================================

  /// Maximum amount of time for which offline mining rewards can be generated.
  ///
  /// The application does not perform background mining.
  /// It calculates simulated rewards when the player returns to the app.
  static const Duration maximumOfflineMiningDuration =
      Duration(hours: 24);

  /// Percentage of normal mining efficiency applied to offline rewards.
  ///
  /// 0.50 means offline rewards operate at 50% of active mining efficiency.
  static const double offlineMiningEfficiency = 0.50;

  /// Minimum elapsed time required before an offline reward is considered.
  static const Duration minimumOfflineMiningDuration =
      Duration(seconds: 10);

  // ===========================================================================
  // Miner progression
  // ===========================================================================

  /// Initial miner level.
  static const int initialMinerLevel = 1;

  /// Maximum miner level.
  static const int maximumMinerLevel = 100;

  /// Initial miner experience.
  static const int initialMinerExperience = 0;

  /// Base XP required for the first level progression.
  static const int baseXpForLevel = 100;

  /// Additional multiplier applied to XP requirements as levels increase.
  static const double xpLevelMultiplier = 1.25;

  // ===========================================================================
  // Miner upgrades
  // ===========================================================================

  /// Initial virtual upgrade cost.
  static const double initialUpgradeCost = 10.0;

  /// Multiplier applied to the previous upgrade cost.
  static const double upgradeCostMultiplier = 1.35;

  /// Mining-power increase provided by the first basic upgrade.
  static const double baseUpgradePowerIncrease = 0.5;

  /// Maximum number of upgrade levels for the base miner.
  static const int maximumUpgradeLevel = 100;

  // ===========================================================================
  // Miner components
  // ===========================================================================

  /// Initial CPU level.
  static const int initialCpuLevel = 1;

  /// Initial GPU level.
  static const int initialGpuLevel = 1;

  /// Initial cooling level.
  static const int initialCoolingLevel = 1;

  /// Initial storage level.
  static const int initialStorageLevel = 1;

  /// Maximum component level.
  static const int maximumComponentLevel = 50;

  /// Mining-power contribution of one CPU level.
  static const double cpuPowerPerLevel = 0.25;

  /// Mining-power contribution of one GPU level.
  static const double gpuPowerPerLevel = 1.0;

  /// Efficiency penalty threshold for insufficient cooling.
  static const double coolingPenaltyThreshold = 0.75;

  /// Maximum virtual storage capacity of the base miner.
  static const double initialStorageCapacity = 1000.0;

  /// Storage capacity added per upgrade level.
  static const double storageCapacityPerLevel = 500.0;

  // ===========================================================================
  // Boosts
  // ===========================================================================

  /// Maximum number of boosts that can be active simultaneously.
  static const int maximumActiveBoosts = 3;

  /// Default boost duration.
  static const Duration defaultBoostDuration =
      Duration(minutes: 10);

  /// Default mining multiplier for a normal boost.
  static const double defaultBoostMultiplier = 2.0;

  /// Maximum allowed mining multiplier.
  static const double maximumBoostMultiplier = 10.0;

  // ===========================================================================
  // Streak
  // ===========================================================================

  /// Number of consecutive days required to establish the first streak.
  static const int initialStreakDays = 1;

  /// Maximum streak multiplier.
  static const double maximumStreakMultiplier = 3.0;

  /// Additional multiplier added per consecutive streak day.
  static const double streakMultiplierIncrement = 0.05;

  // ===========================================================================
  // Daily rewards
  // ===========================================================================

  /// Number of days in a complete daily reward cycle.
  static const int dailyRewardCycleDays = 7;

  /// Base reward for the first day.
  static const double firstDailyReward = 5.0;

  /// Maximum daily reward in one normal cycle.
  static const double maximumDailyReward = 500.0;

  // ===========================================================================
  // Missions
  // ===========================================================================

  /// Maximum number of active missions displayed at once.
  static const int maximumActiveMissions = 5;

  /// Base XP reward for completing a mission.
  static const int baseMissionXpReward = 25;

  /// Base virtual-currency reward for completing a mission.
  static const double baseMissionCoinReward = 2.0;

  // ===========================================================================
  // Achievements
  // ===========================================================================

  /// Base XP reward for unlocking an achievement.
  static const int baseAchievementXpReward = 50;

  /// Base virtual-currency reward for unlocking an achievement.
  static const double baseAchievementCoinReward = 5.0;

  // ===========================================================================
  // Education
  // ===========================================================================

  /// XP awarded after successfully completing an educational lesson.
  static const int lessonCompletionXp = 20;

  /// XP awarded for a correct quiz answer.
  static const int correctQuizAnswerXp = 10;

  /// Bonus XP awarded for completing a quiz without mistakes.
  static const int perfectQuizBonusXp = 50;

  /// Minimum score required to consider a quiz passed.
  static const double quizPassingScore = 0.70;

  // ===========================================================================
  // Quiz
  // ===========================================================================

  /// Maximum number of attempts allowed for one quiz session.
  static const int maximumQuizAttempts = 3;

  /// Maximum number of questions in a standard quiz session.
  static const int maximumQuizQuestions = 10;

  // ===========================================================================
  // Mystery boxes
  // ===========================================================================

  /// Minimum virtual value of a mystery-box reward.
  static const double minimumMysteryBoxReward = 1.0;

  /// Maximum virtual value of a mystery-box reward.
  static const double maximumMysteryBoxReward = 1000.0;

  // ===========================================================================
  // Currency conversion
  // ===========================================================================

  /// Conversion rates are virtual and fixed.
  ///
  /// The actual currency definitions belong to `currencies_data.dart`.
  /// The conversion engine must use those definitions instead of contacting
  /// a real exchange.
  static const bool conversionRatesAreFixed = true;

  /// Prevent conversion from creating an infinite or invalid result.
  static const double maximumConversionResult = 999999999999.0;

  // ===========================================================================
  // Statistics
  // ===========================================================================

  /// Maximum number of mining records retained for local statistics.
  static const int maximumMiningHistoryRecords = 1000;

  /// Maximum number of conversion records retained locally.
  static const int maximumConversionHistoryRecords = 500;

  // ===========================================================================
  // Number precision
  // ===========================================================================

  /// Precision used internally when comparing very small virtual values.
  static const double calculationEpsilon = 0.0000000001;

  /// Number of decimal places used for virtual crypto-like balances.
  static const int currencyDecimalPlaces = 8;

  /// Number of decimal places used for virtual USD values.
  static const int usdDecimalPlaces = 2;

  // ===========================================================================
  // Game safety limits
  // ===========================================================================

  /// Prevents an individual operation from producing an unreasonable reward.
  static const double maximumSingleOperationReward = 1000000.0;

  /// Prevents negative virtual balances.
  static const double minimumBalance = 0.0;

  /// Prevents negative mining power.
  static const double minimumMiningPower = 0.0;

  /// Prevents invalid negative XP.
  static const int minimumExperience = 0;

  // ===========================================================================
  // Virtual economy disclaimer
  // ===========================================================================

  /// Indicates that this application is a simulation.
  static const bool isSimulation = true;

  /// Real cryptocurrency mining is never performed by this application.
  static const bool performsRealMining = false;

  /// Real blockchain transactions are never performed by this application.
  static const bool performsRealTransactions = false;

  /// Real exchange orders are never submitted by this application.
  static const bool performsRealExchangeOrders = false;

  /// Virtual balances have no withdrawable monetary value.
  static const bool balancesHaveRealMonetaryValue = false;
}