/// Centralized keys used by the application's local storage.
///
/// Keeping all storage keys in one place prevents spelling mistakes,
/// duplicated keys, and accidental incompatibilities between repositories
/// and storage implementations.
///
/// IMPORTANT:
/// - Do not rename an existing key casually.
/// - Changing a persisted key can make previously saved user data
///   inaccessible.
/// - If a key must be replaced, a migration should be considered.
abstract final class StorageKeys {
  StorageKeys._();

  // ===========================================================================
  // Storage metadata
  // ===========================================================================

  /// Version of the persisted storage schema.
  static const String schemaVersion = 'storage_schema_version';

  /// Indicates whether initial/default data has been seeded.
  static const String dataSeeded = 'data_seeded';

  // ===========================================================================
  // Player / profile
  // ===========================================================================

  /// Unique local identifier assigned to the player.
  static const String playerId = 'player_id';

  /// Player display name.
  static const String playerName = 'player_name';

  /// Timestamp when the player profile was created.
  static const String profileCreatedAt = 'profile_created_at';

  /// Timestamp of the player's most recent activity.
  static const String lastActiveAt = 'last_active_at';

  // ===========================================================================
  // Game state
  // ===========================================================================

  /// Serialized game state.
  static const String gameState = 'game_state';

  /// Current virtual USDT balance.
  ///
  /// This key is retained separately for compatibility and migration
  /// scenarios. The primary source of truth should normally be GameState.
  static const String usdtBalance = 'usdt_balance';

  /// Total virtual value earned during the lifetime of the profile.
  static const String totalLifetimeEarnings = 'total_lifetime_earnings';

  /// Total number of mining actions performed.
  static const String totalMiningActions = 'total_mining_actions';

  // ===========================================================================
  // Miner
  // ===========================================================================

  /// Serialized miner state.
  static const String miner = 'miner';

  /// Current miner level.
  static const String minerLevel = 'miner_level';

  /// Current mining power.
  static const String miningPower = 'mining_power';

  /// Current miner XP.
  static const String minerExperience = 'miner_experience';

  /// Current miner upgrade level.
  static const String minerUpgradeLevel = 'miner_upgrade_level';

  /// CPU component state.
  static const String cpuLevel = 'cpu_level';

  /// GPU component state.
  static const String gpuLevel = 'gpu_level';

  /// Cooling component state.
  static const String coolingLevel = 'cooling_level';

  /// Storage component state.
  static const String storageLevel = 'storage_level';

  // ===========================================================================
  // Currencies / holdings
  // ===========================================================================

  /// Serialized holdings collection.
  static const String holdings = 'holdings';

  /// Serialized currency data cache.
  static const String currencies = 'currencies';

  /// Timestamp of the last virtual-price update.
  static const String currencyDataUpdatedAt = 'currency_data_updated_at';

  // ===========================================================================
  // Mining
  // ===========================================================================

  /// Timestamp when the current mining session started.
  static const String miningSessionStartedAt = 'mining_session_started_at';

  /// Timestamp when the most recent mining calculation was completed.
  static const String lastMiningCalculationAt =
      'last_mining_calculation_at';

  /// Total virtual reward generated by mining.
  static const String totalMiningReward = 'total_mining_reward';

  /// Serialized mining history.
  static const String miningHistory = 'mining_history';

  // ===========================================================================
  // Offline mining
  // ===========================================================================

  /// Timestamp from which offline mining should be calculated.
  static const String offlineMiningStartedAt = 'offline_mining_started_at';

  /// Timestamp when the user last returned to the application.
  static const String lastOfflineRewardAt = 'last_offline_reward_at';

  /// Last calculated offline reward.
  static const String lastOfflineReward = 'last_offline_reward';

  /// Total virtual rewards generated through offline simulation.
  static const String totalOfflineReward = 'total_offline_reward';

  // ===========================================================================
  // XP / levels
  // ===========================================================================

  /// Current player level.
  static const String playerLevel = 'player_level';

  /// Current total XP.
  static const String totalXp = 'total_xp';

  /// XP already earned in the current level.
  static const String currentLevelXp = 'current_level_xp';

  /// Total XP earned throughout the profile lifetime.
  static const String lifetimeXp = 'lifetime_xp';

  // ===========================================================================
  // Boosts
  // ===========================================================================

  /// Serialized active boosts.
  static const String activeBoosts = 'active_boosts';

  /// Serialized boost inventory.
  static const String boostInventory = 'boost_inventory';

  /// Timestamp when the most recent boost was activated.
  static const String lastBoostActivatedAt = 'last_boost_activated_at';

  // ===========================================================================
  // Missions
  // ===========================================================================

  /// Serialized mission progress.
  static const String missionProgress = 'mission_progress';

  /// IDs of completed missions.
  static const String completedMissionIds = 'completed_mission_ids';

  /// Timestamp of the last mission reset.
  static const String missionResetAt = 'mission_reset_at';

  // ===========================================================================
  // Achievements
  // ===========================================================================

  /// Serialized achievement progress.
  static const String achievementProgress = 'achievement_progress';

  /// IDs of unlocked achievements.
  static const String unlockedAchievementIds =
      'unlocked_achievement_ids';

  // ===========================================================================
  // Education
  // ===========================================================================

  /// Serialized education progress.
  static const String educationProgress = 'education_progress';

  /// IDs of completed lessons.
  static const String completedLessonIds = 'completed_lesson_ids';

  /// Serialized quiz progress.
  static const String quizProgress = 'quiz_progress';

  /// Total number of correctly answered quiz questions.
  static const String correctQuizAnswers = 'correct_quiz_answers';

  /// Total number of quiz attempts.
  static const String totalQuizAttempts = 'total_quiz_attempts';

  // ===========================================================================
  // Daily rewards
  // ===========================================================================

  /// Current day in the daily reward cycle.
  static const String dailyRewardDay = 'daily_reward_day';

  /// Timestamp when the daily reward was last claimed.
  static const String lastDailyRewardAt = 'last_daily_reward_at';

  /// Current consecutive login streak.
  static const String loginStreak = 'login_streak';

  /// Longest consecutive login streak.
  static const String longestLoginStreak = 'longest_login_streak';

  // ===========================================================================
  // Mystery boxes
  // ===========================================================================

  /// Number of mystery boxes currently available.
  static const String mysteryBoxCount = 'mystery_box_count';

  /// Timestamp of the last mystery box claim.
  static const String lastMysteryBoxClaimAt =
      'last_mystery_box_claim_at';

  // ===========================================================================
  // Conversion history
  // ===========================================================================

  /// Serialized virtual currency conversion history.
  static const String conversionHistory = 'conversion_history';

  /// Total number of virtual conversions performed.
  static const String totalConversions = 'total_conversions';

  // ===========================================================================
  // Statistics
  // ===========================================================================

  /// Serialized statistics state.
  static const String statistics = 'statistics';

  /// Total play time represented in seconds.
  static const String totalPlayTimeSeconds = 'total_play_time_seconds';

  /// Number of application sessions.
  static const String totalSessions = 'total_sessions';

  /// Number of days the player has opened the application.
  static const String totalActiveDays = 'total_active_days';

  // ===========================================================================
  // Favorites
  // ===========================================================================

  /// IDs of currencies marked as favorites.
  static const String favoriteCurrencyIds = 'favorite_currency_ids';

  /// IDs of lessons marked as favorites.
  static const String favoriteLessonIds = 'favorite_lesson_ids';

  // ===========================================================================
  // Settings
  // ===========================================================================

  /// Selected application language.
  static const String languageCode = 'language_code';

  /// Selected application theme.
  static const String themeMode = 'theme_mode';

  /// Whether sound effects are enabled.
  static const String soundEnabled = 'sound_enabled';

  /// Whether vibration/haptic feedback is enabled.
  static const String hapticFeedbackEnabled =
      'haptic_feedback_enabled';

  /// Whether notifications are enabled inside supported platforms.
  static const String notificationsEnabled = 'notifications_enabled';

  /// Whether the onboarding flow has already been completed.
  static const String onboardingCompleted = 'onboarding_completed';

  /// Whether educational disclaimer has been acknowledged.
  static const String disclaimerAcknowledged =
      'disclaimer_acknowledged';

  // ===========================================================================
  // App lifecycle
  // ===========================================================================

  /// Timestamp of the first application launch.
  static const String firstLaunchAt = 'first_launch_at';

  /// Timestamp of the most recent application launch.
  static const String lastLaunchAt = 'last_launch_at';

  /// Number of times the application has been launched.
  static const String launchCount = 'launch_count';

  // ===========================================================================
  // Backup / import / export
  // ===========================================================================

  /// Timestamp of the most recent local backup.
  static const String lastBackupAt = 'last_backup_at';

  /// Timestamp of the most recent import.
  static const String lastImportAt = 'last_import_at';

  /// Version of the exported game-state format.
  static const String exportFormatVersion = 'export_format_version';
}